### ISSUE TITLE
Official Intercom Swift Package now available

### ISSUE THREAD

**Issue by Br1an-Boyle** [FelixHerrmann/intercom-ios#3]
Hey @FelixHerrmann 👋🏻 
Brian here from Intercom.
Appreciate you putting this repo together. Just wanted to let you know that we now have an [official Swift Package repo](https://swiftpackageindex.com/intercom/intercom-ios-sp) for Intercom.
Thanks!

**Comment by FelixHerrmann** [comment]
Hi @Br1an-Boyle,
I'm aware of that but thanks for letting me know! Happy to see that this solution is no longer needed and that we have it officially from your side 🙏

I didn't had the time so far to deprecate this repository and there is actually one thing that is holding us back from migrating to your one, it has no license. This is not a functional problem but it will result in that Intercom wouldn't appear in our acknowledgment section... if you could add that that would be awesome!

Let me know and have a great day!

**Comment by Br1an-Boyle** [comment]
We have bundled the licence inside the `xcframework` binary. 
Is there somewhere else you'd want/expect it to be?

**Comment by FelixHerrmann** [comment]
> Is there somewhere else you'd want/expect it to be?

Where [GitHub](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#determining-the-location-of-your-license) and other tools expect it, at the root directory of the repository

**Comment by Br1an-Boyle** [comment]
That repo has a licence now 😄

**Comment by FelixHerrmann** [comment]
Awesome, thank you!! I will prepare the deprecation now!
